version: '3.3'
services:
  vault:
    image: vault
    command: server -dev -dev-root-token-id=1234
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- localhost:8200/v1/sys/health || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 3
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_LOCAL_CONFIG: '{"storage":{"file":{"path":"/data"}}}'
    ports:
    - target: 8200
      published: 8200
    networks:
    - net
    volumes:
    - vault-data:/data
    deploy:
      replicas: 0
  outproxy:
    image: outproxy
    build:
      context: outproxy
      args:
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
    - target: 80
      published: 80
    networks:
    - net
    environment:
      VAULT_ADDR: http://vault:8200
      LISTEN_PORT: 80
      targetScheme: https
      targetHost: dumbserver
    secrets:
    - vault_token
    deploy:
      replicas: 3
    stop_signal: KILL
    stop_grace_period: 1s
  dumbserver:
    image: dumbserver
    build:
      context: dumbserver
      args:
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
    - target: 443
      published: 443
    networks:
    - net
    environment:
      VAULT_ADDR: http://vault:8200
    secrets:
    - vault_token
    deploy:
      replicas: 3
    stop_grace_period: 1s
networks:
  net:
    attachable: true
secrets:
  vault_token:
    file: vault_token.secret
volumes:
  vault-data: